apiVersion: v1
kind: Pod
metadata:
  name: twocontainers
spec:
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
      - name: content
        mountPath: /usr/share/nginx/html
        readOnly: true

  - name: busybox
    image: busybox
    command:
      - sh
      - -c
      - while true; do (hostname; date) > /data/index.html; sleep 1; done
    volumeMounts:
      - name: content
        mountPath: /data
        
  volumes:
  - name: content
